spring:
  application:
    name: macula-iam-application
  redis:
    host: localhost
    port: 6379
    database: 2
  cache:
    type: generic
macula:
  j2cache:
    # Resilience4j Circuit Breaker properties for j2cache
    open-circuit-breaker: true
    circuit-breaker:
      failure-rate-threshold: 25
      slow-call-rate-threshold: 25
      slow-call-duration-threshold: 250ms
      sliding-window-type: count_based
      permitted-number-of-calls-in-half-open-state: 20
      max-wait-duration-in-half-open-state: 5s
      sliding-window-size: 40
      minimum-number-of-calls: 10
      wait-duration-in-open-state: 2500ms

logging:
  level:
    org.macula.iam: TRACE